apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: mdowell
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/mdowell-harbor-project/lab-env-repo/app:decc62e-383bf62
        ports:
        - containerPort: 5000
